# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
import numpy as np

In [2]:
vec = np.zeros(100)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
vec = np.ones(100)
vec

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
vec = np.full(100, 3)
vec

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [5]:
!python3 -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 5. Поменять 2 строки в матрице

In [6]:
mat = np.arange(16).reshape(4, 4)
print(mat)
mat[[0, 1]] = mat[[1, 0]]
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Создать вектор со значениями от 10 до 100

In [7]:
vec = np.arange(10, 101)
vec

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [8]:
vec = np.arange(10)
print(vec)
vec = vec[::-1]
print(vec)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [9]:
mat = np.arange(16).reshape(4, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [10]:

vec = np.arange(1, 6)
vec2 = np.zeros(4*3 + 5)
vec2[::4] = vec
vec2

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [11]:
mat = np.ones((3, 3))
mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [12]:
mat = np.random.random((3, 3, 3))
mat

array([[[0.56485681, 0.39939588, 0.79989236],
        [0.15021351, 0.90207475, 0.10294634],
        [0.3687143 , 0.61588401, 0.72973623]],

       [[0.46885778, 0.98625404, 0.0617194 ],
        [0.78018669, 0.034637  , 0.92534697],
        [0.90394835, 0.5732387 , 0.87418443]],

       [[0.04218011, 0.38969098, 0.32838994],
        [0.54663846, 0.14622981, 0.68302152],
        [0.86466721, 0.63189451, 0.40888718]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [13]:
mat = np.random.random((10, 10))
print(mat.min(), mat.max())

0.0069960734758268694 0.9977510966159765


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
vec = np.random.random(30)
vec.mean()

0.46914964206341936

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [15]:
n, m = 6, 4
mat = np.zeros((n, m))
mat[0, :] = 1
mat[:, 0] = 1
mat[n - 1, :] = 1
mat[:, m - 1] = 1
print(mat)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [16]:
mat = np.diag(np.arange(1, 5), k = -1)
mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [17]:
mat = np.zeros((8, 8))
mat[0::2, 0::2] = 1
mat[1::2, 1::2] = 1
mat

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [18]:
mat = np.ones((6, 7, 8))
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [19]:
mat = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
mat

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [20]:
A = np.full((5, 3), 2)
B = np.full((3, 2), 3)
A@B

array([[18, 18],
       [18, 18],
       [18, 18],
       [18, 18],
       [18, 18]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [21]:
ar = np.array([1, -8, 5, 6, 2, 3, 10])
ar[(ar >= 3) & (ar <= 8)] *= -1
ar

array([ 1, -8, -5, -6,  2, -3, 10])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [22]:
mat = np.tile(np.arange(0, 5), (5, 1))
mat

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [23]:
def my_gen():
    for x in np.arange(10):

ar = np.fromiter(my_gen(), int, count = 6)
ar

array([0, 1, 2, 3, 4, 5])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [24]:
vec = np.linspace(0, 1, 10, endpoint = False)[1:]
vec

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 26. Отсортировать вектор

In [25]:
vec = np.random.random(10)
print(vec)
vec.sort()
print(vec)

[0.46453624 0.7715229  0.77989933 0.43123938 0.20880117 0.94591432
 0.25375719 0.48148309 0.99022345 0.15228318]
[0.15228318 0.20880117 0.25375719 0.43123938 0.46453624 0.48148309
 0.7715229  0.77989933 0.94591432 0.99022345]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [26]:
vec = np.array([1, 5, 8, 10, 3, 2])
vec2 = np.array([1, 5, 8, 10, 3, 2])
print(np.allclose(vec, vec2))

True


#### 28. Сделать массив неизменяемым

In [27]:
ar = np.array([1, 2, 3])
ar.flags.writeable = False
ar = np.append(ar, 10)
ar[3] = 5
print(ar)
# Очень странно метод работает 

[1 2 3 5]


#### 29. Найти n наибольших значений в массиве

In [28]:
n = 3
ar = np.arange(10)[::-1]
ar.sort()
print(ar[-n:])

[7 8 9]


In [29]:
ar = (np.arange(10) + 10)[::-1]
print(np.argpartition(ar, n))

[7 8 9 6 5 4 1 3 2 0]


#### 30. Заменить максимальный элемент на ноль

In [30]:
vec = np.arange(10)
vec[vec.argmax()] = 0
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [31]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [56]:
a = np.arange(5) + 1
b = np.arange(5)[::-1] + 10
c = 1/np.subtract.outer(a, b)
print(c)

[[-0.07692308 -0.08333333 -0.09090909 -0.1        -0.11111111]
 [-0.08333333 -0.09090909 -0.1        -0.11111111 -0.125     ]
 [-0.09090909 -0.1        -0.11111111 -0.125      -0.14285714]
 [-0.1        -0.11111111 -0.125      -0.14285714 -0.16666667]
 [-0.11111111 -0.125      -0.14285714 -0.16666667 -0.2       ]]


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [59]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float16, np.float32, np.float64, np.float128]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308
-1.189731495357231765e+4932
1.189731495357231765e+4932


#### 34. Напечатать все значения в массиве

In [74]:
np.set_printoptions(threshold = None)
mat = np.ones((100, 100))
print(mat)

1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [84]:
ar = np.arange(20) + np.random.random(20)
print(ar)
num = 15
print(ar[np.abs(ar - num).argmin()])


[ 0.51968518  1.98448822  2.43764611  3.66714059  4.79069739  5.36990326
  6.27374943  7.04175662  8.8026623   9.17977914 10.39115582 11.59750787
 12.8749701  13.03612987 14.78860911 15.45866828 16.81510153 17.7768553
 18.96509651 19.26377015]
14.78860910618832


#### 36. Преобразовать массив из float в int

In [87]:
ar = np.linspace(0, 1, 10)
print(ar)
ar.astype(np.int64)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [88]:
ar = np.arange(10)
for ind, elem in np.ndenumerate(ar):
    print(ind, elem)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9


#### 38. Случайно расположить p элементов в 2D массив

In [96]:
p = np.arange(25)
mat2d = np.zeros((5, 5))
np.put(mat2d, p, np.random.choice(p, size = (5, 5)))
mat2d

array([[ 9., 22., 21., 16., 15.],
       [20., 10., 15.,  5., 13.],
       [12.,  7., 19.,  4.,  8.],
       [12.,  0., 14., 22., 14.],
       [ 8.,  2., 11.,  8., 14.]])

#### 39. Отнять среднее из каждой строки в матрице

In [104]:
mat = np.tile(np.arange(10), (5, 1))
print(mat)
mat = mat - mat.mean(axis = 1, keepdims=True)
mat

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


array([[-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5],
       [-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [116]:
p = np.arange(25)
mat2d = np.zeros((5, 5))
np.put(mat2d, p, np.random.choice(p, size = (5, 5)))
print(mat2d)
n = 3
print(mat2d[:, n])
mat2d = mat2d[np.argsort(mat2d[:, n])]
mat2d

[[ 6.  6.  7. 17. 11.]
 [11. 21. 12. 13. 15.]
 [ 0. 22.  6. 11.  3.]
 [ 7. 22.  7.  0. 12.]
 [ 9.  3.  7. 11. 23.]]
[17. 13. 11.  0. 11.]


array([[ 7., 22.,  7.,  0., 12.],
       [ 0., 22.,  6., 11.,  3.],
       [ 9.,  3.,  7., 11., 23.],
       [11., 21., 12., 13., 15.],
       [ 6.,  6.,  7., 17., 11.]])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [146]:
mat = np.ones((5, 5))
mat = np.hstack((mat, np.zeros((5,1))))
print(mat)
print(not mat.all(axis=0).all())
#print(np.info(np.all))

[[1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0.]]
True


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [166]:
ar = np.ones(10)
inds = np.array(list(set(np.random.choice(range(10), size = 3))))
print(inds)
ar[inds] += 1
ar

[8 3 4]


array([1., 1., 1., 2., 2., 1., 1., 1., 2., 1.])

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [183]:
w, h = 3, 4
mat = np.random.randint(0, 256, (w, h), dtype=np.ubyte)
print(mat)
print(len(np.unique(mat)))

[[177  94 176 109]
 [ 86  86 190  17]
 [176 247   1 238]]
10


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [189]:
mat = np.random.random((3, 3, 3, 3))
#print(mat)
print(mat.sum(axis = 3).sum(axis = 2))

[[5.59848407 4.7621323  5.38472801]
 [4.29195007 4.29567473 6.17298899]
 [3.52857462 4.27291179 6.15365048]]
